language: scala
sudo: true
scala:
  - 2.12.8
jdk:
  - oraclejdk8
install: true

services:
  - docker

before_install:
  - docker run -d -p 8000:8000 dwmkerr/dynamodb

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)