language: scala
sudo: true
scala:
  - 2.12.8
jdk:
  - oraclejdk8
install: true

services:
  - docker

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - docker run -d -p 8000:8000 dwmkerr/dynamodb

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy: sbt dist
deploy:
  provider: releases
  api_key:
    secure: vFp6n53Uuz8xrlU79bjSZFRyls7O/xANiNQy2JSgRBRr93uZo/AEm6XTedSal6JUelGVPweGYZKbnx6YGOhkmAV/p4rNfUeP0xJ9m0nirB8aED3QoM5TJ0tkurmz28iGAp5NlVT0KveydTqXRqkT6FIeR6jZQeIOZUSh2XoH/r+luXcIpZbt7KYQAoqF8Q35myvIR3vGmZBpnKWy93TPkD9i2AB/Q0a0wa70fkhEl30WHk8YAW4G2/hKQV6djegvhX0Zl9O/DwCOVYXu37UDz8+/rV75hev84SxXLLYAZiJVprJ4eRSHlZdECs7Zf9ctv2SDiqOVGfX8ZaEVSx6b5orzGnB4r5n4/wYCumA716QAs/YgrLed+nZ3km0paWvuD0CVYbgd+wLGSqSOvkuv1IS2Zw4rkjFVxuNbTQPCH4cv4mZREi6/mE2FQHV7J5EHWfw+N/D2WFH0I1oeDDhw+P7wsK8ocGxztmuwC8CgE3oahXZwQxHz1EX2zLCMd2vuNpo08sbHQNT1qmhyvUqo8WSm0pXf0vNfaTP8nl0ZW4/gYMXJ3+yoqSWAwYzKao0vd9Rq/9Mp5KQX55cm2lJ4ao4WmI5S1TcPZmAJOsZGfloPzUzhbzsr6SL5ZDtGWuxof4py5yiPzkRkV2dnN96nOR4RcgtN3wrwSYf+umtOO8o=
  file: "server/target/universal/*.zip"
  skip_cleanup: true
  on:
    tags: true
