language: scala
sudo: true
scala:
  - 2.12.8
jdk:
  - oraclejdk8
install: true

services:
  - docker

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - docker run -d -p 8000:8000 dwmkerr/dynamodb

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy: sbt dist
deploy:
  provider: releases
  api_key:
    secure: nnuIcB1UdfLqtanDvK0VeGzhmDkmY+phrppGSRqG0nB/cy0RJpUiqliFAKTO4D+GYO8jVxs81unFlrotWvZZdmm7MkjHkfaHpiHHvzfuqjYVFss/AGmFFidMpsgCbr0gl7HPIWIh2IjTUiaWfEO90ZVhcX0NK8VGjs9+ytdRzTx7MY5RLnK9akbvTid8/s6IZcRIiLUS1GGMJv1tyfalWIPuXo/rducKRXP/QFukARijIUDsl0lCTWN3U8ay44c6dMUORQu0FMzT+g5E/EFC/jeyBJPfVYPljKcofXeIJR+Y0Dluk1yK5Y0ahrRrHEUISUQGsV88qBq5eo17UeKvym7dtntVFgZkLkQEZsjdQENQfael+d257GZnTSJeM6BmOrohuN+0ZQQvPLxUEnj7IAPqmqgf8MTone7eEI9MdL1ATRM7/8DzS0NlDzEX7V+Hkb05NFMGcJiuzskzjjMYVKIxTcxCorqUxWsv/4u9T8q3mzpZ04yohrsCcMJ9PTrSTJxdZTVeltAXQJRpzLr8ySsUwDHXWDVt2D2N9m87GwyQyqnaebxxsKygchmrk3wr9qeCwHwOeeMYChfpeB0/izkT7emFm2jZGAlCe8SBhJi3MslejAgT0ClTB+21S6vd0wDwcGgOcG4jph3Dp34NS2JfZEHIawdfkxZMSb2gr74=
  file: server/target/universal/*
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: terdong/car_adverts_service
