language: scala
sudo: true
scala:
  - 2.12.8
jdk:
  - oraclejdk8
install: true

services:
  - docker

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - docker run -d -p 8000:8000 dwmkerr/dynamodb

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy: sbt
deploy:
  provider: releases
  api_key: fQ0nmLn/6pNDOZF33ELj9Z3rDTd2f6Tbi/uoB/v9bbPIATMcXzzoBo+67Qg2IDu70moFFzL3EIraQb/jFhjFejv5ZqJK/62AQU7vJEa3xbfKKTcjX2371UoETC4pLZND4DVjAq8Au+b7bKJzcB0sZAM9ZyY96YHpe/dk2QbLD5RcXj/+qwi81EQ+2Tq/7hZv9v2OS+nTdX4ZqzTqCHsvVH8A3AraSXuoDEcFYgV5+0woVyfqLKyKghb0zxw+PF0GOaMsxhZ0rf/7snfHaUipe/2ZESOuUpucZjly1zQCPcHrep+0+lCvSACHVKkyBfDu/jaEVhaJKuhF1kg9VQ38bU1B3WdzwcUWtekYNXljoL4xRxGxFPXIZVoE9xZSIk0XmUO/UGH03LqwPFzvzJw41nrE4DxLyD88HOb59fQa/LJ7cEzBDdfFpskpaCbsg8hL+MJs+pMhpQESx/zuPVlCgZeieG3HC984bWCnD5xBR3lX6mPF0u46lbUZfELNm7SFli27wetPzqHQuy5clxMJ2DNhSZeEKef5c2p7629jtPUqiSITRahNiYeyoy3T7nrQ/4MrDkHBKQMZ+lN39MIaHh5IdklUTJLeTTuumNFx2fKy2RjaqipTo2BP6k/ZUTwhCymLXMFaGIy6y56NX7kHU5teknYnenHTgkh8G8krnRw=
  file: "server/target/universal/*.zip"
  skip_cleanup: true
  on:
    tags: true